## UDEMY COURSE DATA ANALYSIS PYTHON EXCERCISE

Objective :<br>
Q. 1) What are all different subjects for which Udemy is offering courses ? <br>
Q. 2) Which subject has the maximum number of courses.<br>
Q. 3) Show all the courses which are Free of Cost.<br>
Q. 4) Show all the courses which are Paid. <br>
Q. 5) Which are Top Selling Courses ?<br>
Q. 6) Which are Least Selling Courses ? <br>
Q. 7) Show all courses of Graphic Design where the price is below 100 ?<br>
Q. 8) List out all the courses that are related to 'Python'.<br>
Q. 9) What are courses that were published in the year 2015 ?<br>
Q. 10) What is the Max. Number of Subscribers for Each Level of courses ?<br>

In [1]:
#Library Declaration
import pandas as pd

Importing data procedure

In [2]:
df = pd.read_csv("Udemy.csv")

Basic data exploration to familiarized the data we are working on

In [6]:
df.dtypes

course_id               int64
course_title           object
is_paid                  bool
price                  object
num_subscribers         int64
num_reviews             int64
num_lectures            int64
level                  object
content_duration       object
published_timestamp    object
subject                object
dtype: object

## Listing Subjects in Udemy

In [8]:
df["subject"].value_counts()

Web Development        1200
Business Finance       1199
Musical Instruments     680
Graphic Design          603
Name: subject, dtype: int64

From above code can be concluded there are **4 Subjects** covered in Udemy with **Web Development** has the maximum number of courses

## Evaluating Paid or Free Course

In [11]:
#Showing Free Course
df[df["is_paid"]==0].reset_index()

,index,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,41,286070,5 lecciones que todo guitarrista debe tomar,False,Free,4452,263,14,Beginner Level,1 hour,2014-08-23T05:08:14Z,Musical Instruments
1,49,696630,"7 Ways A Beginner Guitarist Can Sound Better, ...",False,Free,4529,193,7,Beginner Level,36 mins,2015-12-21T18:50:50Z,Musical Instruments
2,57,955914,A beginner`s guide to fingerpicking and strumm...,False,Free,3481,29,20,Beginner Level,2 hours,2016-09-13T21:51:59Z,Musical Instruments
3,67,270976,A how to guide in HTML,False,Free,7318,205,8,Beginner Level,35 mins,2014-08-10T20:19:10Z,Web Development
4,74,1214144,Â¡Triunfar en La Bolsa de Valores No Requiere d...,False,Free,338,7,6,Beginner Level,1 hour,2017-05-30T14:30:12Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...,...
305,3620,552598,WordPress in under an hour - Create/manage you...,False,Free,6474,86,15,All Levels,1 hour,2015-07-15T00:21:56Z,Web Development
306,3638,1068590,Wordpress Website Mastery 2017,False,Free,5181,64,22,Beginner Level,2.5 hours,2017-01-18T17:01:40Z,Web Development
307,3652,752706,Write quicker HTML5 and CSS 3; productivity ha...,False,Free,13016,286,15,All Levels,1.5 hours,2016-03-03T17:45:31Z,Web Development
308,3674,1257976,Your First 10 Guitar Lessons - Learn how to pl...,False,Free,924,4,18,Beginner Level,1 hour,2017-06-29T00:29:36Z,Musical Instruments
309,3680,1225194,Zoho Books Gestion FinanciÃ¨re d'Entreprise pas...,False,Free,229,0,33,All Levels,2 hours,2017-05-26T16:45:55Z,Business Finance

In [12]:
#Showing Paid Course
df[df["is_paid"]==1].reset_index()

,index,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments
3,3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21T23:48:18Z,Musical Instruments
4,4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21T23:44:49Z,Musical Instruments
...,...,...,...,...,...,...,...,...,...,...,...,...
3367,3676,498488,Your First Successful Forex Trades - With Case...,True,200,1079,34,16,All Levels,2.5 hours,2015-05-26T20:48:48Z,Business Finance
3368,3677,328960,Your Own Site in 45 Min: The Complete Wordpres...,True,120,1566,29,36,All Levels,4 hours,2015-04-20T22:15:17Z,Web Development
3369,3678,552700,Your Second Course on Piano: Two Handed Playing,True,70,1018,12,22,Beginner Level,5 hours,2015-10-26T20:04:21Z,Musical Instruments
3370,3679,631754,Zend Framework 2: Learn the PHP framework ZF2 ...,True,40,723,130,37,All Levels,6.5 hours,2015-11-11T18:55:45Z,Web Development
3371,3681,964478,Zombie Apocalypse Photoshop Actions,True,50,12,1,15,All Levels,1.5 hours,2016-09-26T22:19:48Z,Graphic Design

In [16]:
#Top 10 most selling
df.sort_values('num_subscribers',ascending = False).head(10)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
2230,41295,Learn HTML5 Programming From Scratch,False,Free,268923,8629,45,All Levels,10.5 hours,2013-02-14T07:03:41Z,Web Development
776,59014,Coding for Entrepreneurs Basic,False,Free,161029,279,27,Beginner Level,3.5 hours,2013-06-09T15:51:55Z,Web Development
3385,625204,The Web Developer Bootcamp,True,200,121584,27445,342,All Levels,43 hours,2015-11-02T21:13:27Z,Web Development
640,173548,Build Your First Website in 1 Week with HTML5 ...,False,Free,120291,5924,30,Beginner Level,3 hours,2014-04-08T16:21:30Z,Web Development
3316,764164,The Complete Web Developer Course 2.0,True,200,114512,22412,304,All Levels,30.5 hours,2016-03-08T22:28:36Z,Web Development
1388,19421,Free Beginner Electric Guitar Lessons,False,Free,101154,1042,95,Beginner Level,4.5 hours,2012-06-15T17:00:33Z,Musical Instruments
3556,473160,Web Design for Web Developers: Build Beautiful...,False,Free,98867,6512,20,All Levels,3 hours,2015-04-13T18:29:47Z,Web Development
2233,94430,Learn Javascript & JQuery From Scratch,True,30,84897,2685,10,All Levels,2 hours,2013-10-10T15:19:29Z,Web Development
2886,130064,Practical PHP: Master the Basics and Code Dyna...,False,Free,83737,4598,45,All Levels,6.5 hours,2014-07-19T03:02:05Z,Web Development
2034,364426,JavaScript: Understanding the Weird Parts,True,175,79612,16976,85,All Levels,11.5 hours,2015-03-12T23:19:54Z,Web Development

In [17]:
df.sort_values('num_subscribers',ascending = True).head(10)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
649,1233314,Building a Balanced Scorecard,True,50,0,0,11,Intermediate Level,2 hours,2017-07-03T21:38:22Z,Business Finance
3259,1232282,The Cash Flow Statement - An Introduction,True,50,0,0,10,Beginner Level,1.5 hours,2017-06-28T16:05:51Z,Business Finance
3261,1275872,The Complete Adobe Spark Course,True,150,0,0,29,All Levels,2 hours,2017-07-03T17:39:57Z,Graphic Design
910,726314,Create Beautiful Image Maps for Your Website,True,20,0,0,8,Intermediate Level,37 mins,2016-01-18T17:56:36Z,Graphic Design
3328,715476,The Cuckoo Strategy to get European Funding,True,160,0,0,6,All Levels,1 hour,2016-01-06T02:38:23Z,Business Finance
1325,1187084,Forex how traders beat the markest with little...,True,100,0,0,16,All Levels,1 hour,2017-07-06T21:16:13Z,Business Finance
2596,185526,MicroStation - CÃ©lulas,True,20,0,0,9,Beginner Level,37 mins,2014-04-15T21:48:55Z,Graphic Design
2597,185526,MicroStation - CÃ©lulas,True,20,0,0,9,Beginner Level,37 mins,2014-04-15T21:48:55Z,Graphic Design
848,1232390,Corporate Ethics,True,100,0,0,13,Beginner Level,3.5 hours,2017-07-03T21:39:13Z,Business Finance
2900,995384,Professional Business Logo Design Using Free O...,True,20,0,0,5,All Levels,37 mins,2016-10-31T16:09:48Z,Graphic Design

In [27]:
# Graphic Design Course cost less than 100
df['price'] = pd.to_numeric(df.price)
df[(df['subject']== 'Graphic Design') & (int(df.price) < 100)]

ValueError: Unable to parse string "Free" at position 41